// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfswwszpgxpwzxyvscjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmc3d3c3pwZ3hwd3p4eXZzY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzEzNjgsImV4cCI6MjA2MzMwNzM2OH0.7-B4U07rNGftyMMf72KOxgeV6XXySUSQFFCfv8t1Z_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);